### ISSUE TITLE
Questions about configs

### ISSUE THREAD

**Issue by Berstanio** [anyicomplex/gdx-graalhelper#1]
Hey,
I'm currently implementing a native-image backend for iOS. I'm curios about your reflection config! 

1. Can you estimate how complete the reflection collection for libGDX is?
2. Is the whole json serialization supported or does it need extra configuration?
3. You include all subclasses and constructors etc. for reflection access. How much bigger is the resulting image with this approach in contrast to specific created configs with the native image agent?
4. Extensions like e.g. are not supported, right? If you want you can take a look here, I made a feature for bullet: https://github.com/Berstanio/libgdx/blob/metal/backends/gdx-backend-moe/src/com/badlogic/gdx/backends/svm/ConfigCollectionFeatureBullet.java

Thanks in advance!

**Comment by anyicomplex** [comment]
1. At least 70% in conservative estimate.
2. All new json serialization features need extra configuration. You can also do it with my helper library, for example, see [here](https://github.com/anyicomplex/unlucky-ae/blob/master/lwjgl3/src/main/java/com/anyicomplex/unlucky/lwjgl3/CustomReflectionFeature.java).
3. At least 25M bigger.
4. Support for official plugins is planned.

Thank you for your support :D

**Comment by Berstanio** [comment]
Okay, thanks for the insights!
Since I'm also implementing a native-image ios backend and it would be a bit unecessary to do double work, what do you think about splitting your repo artifatcts a bit up into core, different extensions and different backends. With that the end user would just need to define the different artifacts dependencies depending on what they is using.
(Hope it gets clear what I mean, I'm not a native speaker!)

If you agree with this, I would be happy to create a pr for my changes specific to the ios backend and bullet!

**Comment by anyicomplex** [comment]
Sorry for not replying to you until now...
(I've been addicted to Mirage Realms lately so I haven't been on GitHub for a few days)

I can't agree more with your idea! 
(I'm not a native speaker too XD)

**Comment by anyicomplex** [comment]
I will finish work on several official libGDX plugins in the near future (conservatively within a week) :D

**Comment by Berstanio** [comment]
> Sorry for not replying to you until now...

No problem!


> I can't agree more with your idea!

Great! I opened a quick and maybe not so clean pr for discussion.


> I will finish work on several official libGDX plugins in the near future (conservatively within a week) :D

Okay, thats nice to hear!

**Comment by Berstanio** [comment]
Hey,
where you already able to publish it to maven central? I wasn't able to find the artifacts.

**Comment by anyicomplex** [comment]
I've failed to do it XD
I wanna publish with GitHub Actions, but the defined project secrets always empty (I use it to store signing key)
I'm greenhand of GitHub......

**Comment by anyicomplex** [comment]
I've resolved problems, now the artifacts should be able to found at Maven Central XD

**Comment by anyicomplex** [comment]
Many thanks :D
The repo is published to s01.oss.sonatype.org now, and may needs some time to sync to Maven Central.

**Comment by Berstanio** [comment]
Perfect!!
